{{- $root := . -}}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $root.Values.namespace }}
type: Opaque
data:
  {{- range $key, $info := $secret.content }}
  {{ $info.key }}: {{ $info.data | b64enc   }}
  {{- end }}
{{- end }}